version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET="blablablacksheepapachaapacheramericangottallent"
      - ADMIN_SECRET_KEY="2025superadmin123456789v1"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: always